### ISSUE TITLE
No matching stream found

### ISSUE THREAD

**Issue by jchia** [azrafe7/vlc4youtube#3]
I get this error when I click on the extension button while on a Youtube page:
```
No matching stream found (Error: Error parsing config: Unexpected token ; in JSON at position 42004).
```
This is on Chrome 81.0.4044.138 on Ubuntu 20.04.

When I visit http://localhost:8080/ I get a VLC interface for controlling playback.

**Comment by azrafe7** [comment]
Hey, thanks for reporting it.

This should have been fixed with the latest changes. 
The extension (new version 0.3.1) is in "pending review" state from google right now.
Let me know if it'll work fine for you (when it will be available), and feel free to close the issue if that's the case.

**Comment by jchia** [comment]
It works now.
